
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: npm install
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # Run linting
      - run:
          name: Run linting
          command: npm run lint || echo "No lint script found, skipping"
      
      # Run tests
      - run:
          name: Run tests
          command: npm run test || echo "No test script found, skipping"
      
      # Build the app
      - run:
          name: Build application
          command: npm run build
          environment:
            VITE_OPENAI_API_KEY: ${OPENAI_API_KEY_DEV}
      
      # Store build artifacts
      - store_artifacts:
          path: dist
          destination: build
          
  deploy-dev:
    docker:
      - image: cimg/node:18.16.0
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: npm install
      
      - run:
          name: Build for development environment
          command: npm run build
          environment:
            VITE_OPENAI_API_KEY: ${OPENAI_API_KEY_DEV}
      
      # Here you would add your deployment commands
      # For example, deploying to Netlify, Vercel, AWS, etc.
      - run:
          name: Deploy to development environment
          command: |
            echo "Deploying to development environment"
            # Add your deployment commands here
            # Examples:
            # - netlify deploy --dir=dist --prod
            # - aws s3 sync dist s3://your-bucket-name/
            echo "Deployment complete"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: main
